import spacy
nlp = spacy.load("en_core_web_sm")
long_text="""
AIROBRAIN fly above the sky AIROBRAIN An Artificial Brain AIROBRAIN Home About Open Source projects collaboration free services neurons BUT Artificial WE WORK with intelligence where intelligent humans make intelligent brains Your browser does not support the video tag. we also work on web development WebWizard WE OFFER a wide range of Website design services in India including business website designing, personal blogs, web portals designing, micro websites, flash websites, e-commerce websites designing, static websites,across all categories & sectors. Email:airobrain@gmail.com Copyright ©️ AIROBRAIN 2023
AIROBRAIN ABOUT US ? THIS IS WHAT WE DO AIROBRAIN Home About Open Source projects collaboration free services AIROBRAIN fly above the sky AIROBRAIN Email:airobrain@gmail.com Copyright ©️ AIROBRAIN 2023
AIROBRAIN AIROBRAIN ACHIVED AIROBRAIN Home About Open Source projects collaboration free services AN AI PROGRAM THAT PREDICTS SEQUENCE THE NEXT NUMBER ! This smart program predicts the next number in the given SEQUENCE 
                            This program predicts next number in given sequence Don't know what exactly i should call is but this program gonna understand the sequence by learning from the given set of numbers
For eg : if 1,2,3 so its an easy sequence the next number is obviously going to be 4 even a kid can answer it But when thing become complex like 1,2,5,6,9,10,? Whats next number is going to be by taking some time and calculation a human can also answer it but this program is gonna be supper fast in that and answer in MS But things are going to be more complex ,next number is 13

43,32,23,15,8,? Sequence became more complex so it requires some better iq to be fast and calculate for humans but this program can just ...... . . . But things became more complex it was difficult for me too to decode

As to teach somebudddy teacher should be able to solve 😅 thats y my program also unable to solve some problems

Like 15,29,56,108,208....expected answer is 400 behind this there is some complex logic i have decoded this answer but dont know how to teach this im searching for algorithms to teach my program AN SINMPLE WINDOWS APPLICATION WHERE IS THE MOUSE ? This is an windows CMD based application written in python and build into .exe file This program find the exact location of the pointer and returns the in the form of x & y coordinates. QRcode-generator for terminal can create an QRCODE ! This is an terminal based python oriented qrcode generator specially made for mobile users
                            this program can create an QR code for an any given text that too without an GUI this python program can run on your mobile device and allows you to save an copy of it learn more by clicking on this link . Email:airobrain@gmail.com Copyright ©️ AIROBRAIN 2023
AIROBRAIN AIROBRAIN WE collaborate AIROBRAIN Home About Open Source projects collaboration free services AIROBRAIN WE'RE collaborating AIROBRAIN is a team of passionate and skilled professionals who are eager to collaborate with others in the fields of artificial intelligence (AI), machine learning (ML), deep learning (DL), video editing, programming, marketing and design. We have expertise in various programming languages and frontend technologies, as well as other useful skills that can help you achieve your goals. If you are interested in working with us or learning more about our projects, please contact us at airobrain@gmail.com. We look forward to hearing from you! Email:airobrain@gmail.com Copyright ©️ AIROBRAIN 2023
AIROBRAIN ABOUT US ? THIS IS WHAT WE DO AIROBRAIN Home About Open Source projects collaboration free services QRcode generator Free QRcode generator that to with no annoying ads !!!! click below link check it out Airobrain search engine free search engine powered by Innoovatum check it out Email:airobrain@gmail.com Copyright ©️ AIROBRAIN 2023
sayeed khan Jefreonsyed contact me JEFREONSYED sayeed About Contact Hire us hello 👋 I am sayeed khan i like teaching machines coffee and cigarettes contact me 🏫 pursuing Engineering at M.S. Ramaiah Institute of Technology. 💼 worked as an ML Engineer intern @innovatum. 🎓 Diploma in cse, specialized in AI and ML. Give me a problem, 24 hours, coffee, and machine running Linux 🐧. JavaScript Python Java MongoDB Docker Transformers Django PyTorch TensorFlow I believe in passion and creativity Your imagination fuels the future let AI take care of the details. Career Winners history jefreonsyed@gmail.com +91 8660959495 LinkedIn instagram github we can do any thing that turns blue when you click it sayeed khan ©️ 2024. All rights reserved. designed by sayeed khan Intro Tech hobbis Contact hobbis
QR Code Generator | AIROBRAIN QR Code Generator by AIROBRAIN Paste a url or enter text to create QR code Generate QR Code
sayeed khan Jefreonsyed contact me JEFREONSYED sayeed About Contact Hire us hello 👋 I am sayeed khan i like teaching machines coffee and cigarettes contact me 🏫 pursuing Engineering at M.S. Ramaiah Institute of Technology. 💼 worked as an ML Engineer intern @innovatum. 🎓 Diploma in cse, specialized in AI and ML. Give me a problem, 24 hours, coffee, and machine running Linux 🐧. JavaScript Python Java MongoDB Docker Transformers Django PyTorch TensorFlow I believe in passion and creativity Your imagination fuels the future let AI take care of the details. Career Winners history jefreonsyed@gmail.com +91 8660959495 LinkedIn instagram github we can do any thing that turns blue when you click it sayeed khan ©️ 2024. All rights reserved. designed by sayeed khan Intro Tech hobbis Contact hobbis
"""
doc=nlp(long_text)
sentences = [sent.text for sent in doc.sents]
chunk_size = 5
chunks = [''.join(sentences[i:i+chunk_size]) for i in range(0,len(sentences),chunk_size)]
for i,chunk in enumerate(chunks):
      print(f"Chunk{i+1}:\n{chunk}\n")